### ISSUE TITLE
[Data Structure] Binary search tree

### ISSUE THREAD

**Issue by Rizzen** [Sharpach/Algorithms#3]
BST implementation

**Comment by willwolfram18** [comment]
Are there any additional requirements for writing the BST implementation?

**Comment by Rizzen** [comment]
> 
> 
> Are there any additional requirements for writing the BST implementation?

It must be BST, tests should be written. You allowed to use any language. If you use C# - preferable test framework - xUnit.

**Comment by willwolfram18** [comment]
Alright, so BST written in C# which includes xUnit tests. Consider it done!
