### ISSUE TITLE
[Algorithm] Knuth–Morris–Pratt string-searching algorithm

### ISSUE THREAD

**Issue by Rizzen** [Sharpach/Algorithms#9]
https://en.wikipedia.org/wiki/Knuth%E2%80%93Morris%E2%80%93Pratt_algorithm

**Comment by cathreya** [comment]
Should the code be only in C#?

**Comment by Rizzen** [comment]
> 
> 
> Should the code be only in C#?
You allowed to use any language, in this case, place it in separated folder in the repo root

**Comment by Rizzen** [comment]
Closed https://github.com/Sharpach/Algorithms/pull/14
